= Секция № 1. Инструменты.

:toc:

Инструменты важны для каждого разработчика. Если ты тратишь время на то, чтобы разобраться с правильными инструментами, на самом деле ты экономишь время, которое будешь тратить на написание и отладку кода. В этой секции будут рассмотрены основные полезные инструменты.

== 1. Make

Программа `make` обычно используется для построения других програм. Когда ты запускаешь `make`, программа ищет в текущей директории файл `Makefile` и выплняет правила записаные в нём на особом языке.

----
my_first_makefile_rule:
    echo "Hello world"
----

Строительными блоками в `make` служат *правила*. Представленное правило состоит из *цели* (`my_first_makefile_rule`) и *рецепта* (`echo "Hello world"`). Если нужно получить от `make` цель, то нужно запустить в терминале `make my_first_makefile_rule`, это приведёт к тому, что `make` отыщет в `Makefile` запрошеное правило и выполнит соответствующий рецепт — напечатает `Hello world`. Рецепты состоят из команд терминала, можешь попробовать выполнить отдельно `echo "Hello world"` и посмотреть что получится.

Правила могут содержать *зависимости* — те цели, которые необходимо выполнить до выполнения текущего правила. В следующем примере правило `task_two` имеет единственную зависимоть: `task_one`. Если выполнить в терминале `make task_two`, то `make` сначала выполнит `task_one`, а затем `task_two`.

----
task_one:
    echo 1
task_two: task_one
    echo 2
----

=== 1.1. Некоторые факты про `make`

* Если запустить `make` не указывая цель, то из `Makefile` будет выбрана первая цель.
* По соглашению названия целей обычно соответствуют именам файлов. Если файл-цель существует и время его модификации больше, чем время модификации _всех_ его зависимостей, то `make` пропустит рецепт из этого правила. Если файл-цель не существует, `make` будет считать, что время модификации этой цели «начало времен» (минимально возможная в данной системе дата и время). Однако временная метка цели, это время последней модификации соответствующего файла.
* Если запустить `make clean` (служебное действие по удалению созданых файлов), то рецепт будет исполняться каждый раз, поскольку файл `clean` никогда не будет создан. (Для более устойчивой работы попробуй использовать `.PHONY` — интернет в помомщь.)
* Отступы в `Makefile` должны быть табами, а не пробелами.
* Рецепты можно запускать параллельно (одновременно) — `make -j 4` (в данном случае четыре параллельных задачи).
* `make` может создавать правила автоматически, если иное не указано. Например, можешь создать файл `my_program.c` и даже без `Makefile` программа `make` сможет его скомпилировать — `make my_program`.
* Язык правил `Makefile` довольно разнообразен, зачатую можно встретить специальные переменные `$@` и `$<`. Посмотри в интернете зачем они.

== Git
=== Команды для запоминания

== GDB
=== Команды для запоминания

== Отладка программ в Linux
=== strace и ltrace
=== catchsegv
=== top
=== ps
=== pidof и pgrep
=== proc
=== lsof
=== netstat и ip
=== kill, pkill и killall
